### ISSUE TITLE
Make base ID of 0 invalid

### ISSUE THREAD

**Issue by LeStarch** [nasa/fpp#346]
Choosing a base ID of `0` is invalid in many cases.  This is because a qualified event ID of `0` causes an assertion failure.   It would be nice if FPP could validate that users do not select component base ID of 0 to avoid such problems.

**Comment by bocchino** [comment]
This seems like a good idea in many cases, but I'm concerned that on a small embedded system with U8 opcodes this approach will disable an opcode that would otherwise be valid. Where is the prohibition on event ID zero coming from? Is it a FSW assertion in a component? Could we address this issue by clearly documenting the component? Otherwise we will impose the restriction even on topologies that don't use the component.

@timcanham Your thoughts?

**Comment by LeStarch** [comment]
ActiveLogger imposes this restriction.

**Comment by JackNWhite** [comment]
Why would this be "a good idea in many cases"? Why would it be a good idea in any case? It feels like it just artificially removes a usable ID and may hinder interaction with other systems.

**Comment by timcanham** [comment]
When I originally implemented `ActiveLogger`, I implemented ID filters by creating an array of integers to track which IDs were filtered and which weren't. A non-zero value in that element of the array meant an ID was filtered, and a zero value meant the filter slot wasn't used. That's why if you use `ActiveLogger`, you can't use `0` as an event ID. `ActiveLogger` could be updated to use a more sophisticated filter data structure that would allow the use of `0` as an ID. @bocchino's point is that on small systems were you don't have a big ID space it would be nice to have it available, but so far we haven't had a deployment that restricted. @LeStarch can put an update for `ActiveLogger` in the roadmap if this is a big issue.

**Comment by bocchino** [comment]
This seems like an ActiveLogger issue and not an FPP issue. I'm going to close the issue here.
